config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'sessions#new'
  get 'history', to: 'home#history'
  get 'clear_history', to: 'home#clear_history'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :content, presence: true # , length: { maximum: 50 }

  scope :latest, -> { last(15) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path, alert: 'You must be logged in to perform that action' unless logged_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @users = User.all
    @messages = Message.latest
  end

  def history; end

  def clear_history
    Message.where(user: @current_user).delete_all
    redirect_to history_path, notice: 'All messages successfully deleted'
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast('chat_channel', message: message_render(message))
    else
      redirect_to root_path, alert: 'Something went wrong'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def message_render(message)
    render(partial: 'home/message', locals: { msg: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]
  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      user.toggle!(:status)
      redirect_to root_path, notice: "You have successfully logged in #{user.status}"
    else
      flash.now[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def destroy
    current_user.toggle!(:status)
    session[:user_id] = nil
    redirect_to login_path, notice: 'You have successfully logged out'
  end

  private

  def logged_in_redirect
    redirect_to root_path, alert: 'You are already logged in' if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/_message.html.slim
.event
  .content
    .summary
      em= msg.user.username
      | : 
      = msg.content
      .date
        = time_ago_in_words(msg.created_at)
        |  ago

app/views/home/_user.html.slim
- if user.status?
  = link_to  user.username, root_path, class: "#{logged_in? && current_user == user ? 'item active orange' : 'item'}"

app/views/home/history.html.slim
h4.ui.center.aligned.medium.icon.header
  i.circular.history.orange.icon
  = "History of #{@current_user.username}'s messages"

.ui.fluid.raised.card.chatbox
  div class='content' id='messages'
    div class='ui feed' id='message-container'
      - @current_user.messages.each do |msg|
        = render 'home/message', msg: msg

= link_to  "clear history", clear_history_path

app/views/home/index.html.slim
h4.ui.center.aligned.medium.icon.header
  i.circular.coffee.orange.icon
  | Say something
  
/ .ui.two.column.grid

/   .twelve.wide.column
.ui.fluid.raised.card.chatbox
  div class='content' id='messages'
    div class='ui feed' id='message-container'
      - @messages.each do |msg|
        = render 'home/message', msg: msg
  .extra.content
    = form_for(@message, html: {class: 'ui reply form'}, url: message_path, remote: true) do |f| 
      .field
        .ui.fluid.icon.input
          = f.text_field :content
          = f.button '<i class="icon edit orange inverted"></i>'.html_safe


  / .four.wide.column

  /   .ui.fluid.raised.card.chatbox.inverted.vertical.menu 
  /     - @users.each do |user|
  /       = render 'home/user', user: user

app/views/layouts/_footer.html.slim
.ui.vertical.footer.segment
  .ui.center.aligned.container
    .ui.stackable.grid
      .seven.wide.column
        h4.ui.header.grey
          | © A.E.V., 
          = "#{Time.now.year}"
          |  SPb. @ 59.799,30.637
      .three.wide.right.floated.column
        .ui.link.list
          = mail_to 'i.dwanderer@gmail.com', 'i.dwanderer@gmail.com', class: 'item'
      .three.wide.right.floated.column
        .ui.link.list
          a.item target="_blank" rel="noopener noreferrer" href="http://github.com/ext-nomad/messenger" GitHub Repo

app/views/layouts/_header.html.slim
.ui.pointing.small.inverted.menu
  .ui.container
    - if logged_in?
      = link_to  "Chatroom", root_path, class: "item #{'active' if current_page?(root_path)}"
      = link_to  "History", history_path, class: "item #{'active' if current_page?(history_path)}"
    .right.menu
      .item
        .ui.inverted.orange.button.dropdown
          - if logged_in?
            = current_user.username
          - else
            | Account
          i.dropdown.icon
          .menu
            - if logged_in?
              = link_to  "Log Out", logout_path, method: 'delete', class: "item"
            - else
              = link_to  "Log In", login_path, class: "item #{'active' if current_page?(login_path)}"
              a.item Sign Up

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  div class=("ui #{name.to_s == 'notice' ? 'success' : 'error'} message")
    i.close.icon
    .header
      = msg

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Messenger
    = favicon_link_tag 'icon.ico'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
  body
    header
      = render 'layouts/header'

    main
      .ui.container
        = render 'layouts/messages'
        = yield

    footer
      = render 'layouts/footer'